208 update rxjava to rxjava2, also target sdk and build tools for latest stable Android Studio
artem-zinnatullin/qualitymatters pull request #223
Opened 2017-10-21 21:56 UTC by Yurii-Laguta

Removed  : rxJavaProguardRules   as per comment on that repo that it's not required for RxJava 2

2017-10-22 05:55 UTC, artem-zinnatullin commented on dependencies.gradle
> +        rxJava                       : '2.1.5',
You can't just update RxJava 1 to 2, it requires code changes :)

2017-10-22 05:55 UTC, artem-zinnatullin commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip
This alone does not update `gradle/wrapper/gradle-wrapper.jar` and `gradlew` files

You'll need to run Gradle, ie `./gradlew --version`

2017-10-22 05:55 UTC, artem-zinnatullin commented on dependencies.gradle
> +        buildTools                   : '25.0.3',
This requires update of `.travis.yml`

2017-10-22 05:56 UTC, artem-zinnatullin commented
Lemme update could CI related stuff, so such changes could be easier to merge

2017-11-16 23:03 UTC, vanniktech requested changes
If we update already from 23 to 25 let's do 27 because why not 🤷‍♂️

2026-06-19 06:07 UTC, yurilaguta commented
Abandoned.

2026-06-19 06:07 UTC, closed without merging